apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    tags: "exec"
  name: "vrt-events-metadata"
  labels:
    app: "vrt-events-metadata"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "vrt-events-metadata-${env}"
      namespace: "vrt-intake"
      labels:
        app: "vrt-events-metadata"
        app.kubernetes.io/component: "vrt-events-metadata-${env}"
        app.kubernetes.io/instance: "vrt-events-metadata-${env}"
        app.kubernetes.io/name: "vrt-events-metadata"
        app.kubernetes.io/part-of: "vrt-events-metadata"
        app.openshift.io/runtime: "vrt-events-metadata"
        app.openshift.io/runtime-version: "${env}"
        env: ${env}
    spec:
      ports:
        - protocol: TCP
          port: ${{svc_port}}
          targetPort: ${{svc_port}}
          name: http
      selector:
        app: "vrt-events-metadata-${env}"
      clusterIP:
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
        image.openshift.io/triggers: >-
          [{'from':{'kind':'ImageStreamTag','name':'vrt-events-metadata:${env}','namespace':'vrt-intake'},'fieldPath':'spec.template.spec.containers[?(@.name==\'vrt-events-metadata-${env}\')].image','pause':'false'}]
      name: "vrt-events-metadata-${env}"
      namespace: "vrt-intake"
      labels:
        app: "vrt-events-metadata"
        app.kubernetes.io/component: "vrt-events-metadata-${env}"
        app.kubernetes.io/instance: "vrt-events-metadata-${env}"
        app.kubernetes.io/name: "vrt-events-metadata"
        app.kubernetes.io/part-of: "vrt-events-metadata"
        app.openshift.io/runtime: "vrt-events-metadata"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: "vrt-events-metadata-${env}"
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: "vrt-events-metadata-${env}"
            deploymentconfig: "vrt-events-metadata-${env}"
            env: ${env}
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
        spec:
          containers:
            - name: "vrt-events-metadata-${env}"
              terminationMessagePath: /dev/termination-log
              resources:
                limits:
                  cpu: '${cpu_limit}m'
                  memory: '${memory_limit}Mi'
                requests:
                  cpu: '${cpu_requested}m'
                  memory: '${memory_requested}Mi'
              ports:
                - containerPort: ${{svc_port}}
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              terminationMessagePolicy: File
              envFrom:
                - configMapRef:
                    name: "vrt-events-metadata-${env}"
              image: >-
                image-registry.openshift-image-registry.svc:5000/vrt-intake/vrt-events-metadata:${env}
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: "vrt-events-metadata-${env}"
      namespace: "vrt-intake"
      labels:
        app: "vrt-events-metadata"
        app.kubernetes.io/component: "vrt-events-metadata-${env}"
        app.kubernetes.io/instance: "vrt-events-metadata-${env}"
        app.kubernetes.io/name: "vrt-events-metadata"
        app.kubernetes.io/part-of: "vrt-events-metadata"
        app.openshift.io/runtime: "vrt-events-metadata"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    data:
      RABBITMQ_USERNAME: some_value
      RABBITMQ_PASSWORD: some_value
      RABBITMQ_HOST: some_value
      RABBITMQ_QUEUE: some_value
      RABBITMQ_PREFETCH_COUNT: some_value
      RABBITMQ_EXCHANGE: some_value
      RABBITMQ_GET_SUBTITLES_ROUTING_KEY: some_value
      MEDIAHAVEN_PASSWORD: some_value
      MEDIAHAVEN_HOST: some_value
      MEDIAHAVEN_USERNAME: some_value
      FTP_HOST: some_value
      FTP_USER: some_value
      FTP_PASSWORD: some_value
parameters:
  - name: env
    value: "env"
  - name: "memory_requested"
    value: "128"
  - name: "memory_limit"
    value: "328"
  - name: "cpu_requested"
    value: "100"
  - name: "cpu_limit"
    value: "300"
  - name: "svc_port"
    value: "8080"